$entry_background_color = rgba(0f0f0fd9)
$entry_color = rgba(d9d9d9d9)
$text_color = rgba(000000ff)
$font_family = JetBrains Mono
$font_family_clock = JetBrains Mono

background {
    path = ~/Pictures/wallpaper/M3-2.png
    blur_size = 1
    blur_passes = 1
    brightness = 0.33
}
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.1
    dots_spacing = 0.3
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color
    fade_on_empty = true

    position = 0, 120
    $entry_background_color = 0x1a1110ff
    $entry_color            = 0xffb4a8ff
    $text_color             = 0xffffffdd
    halign = center
    valign = bottom
}

label { # Clock
    monitor =
    text = $TIME
    color = 0xffffffff
    font_size = 64
    font_family = $font_family_clock

    position = 0, 160
    halign = center
    valign = center
}
label { # Date
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = 0xffffffff
    font_size = 16
    font_family = $font_family

    position = 0, 100
    halign = center
    valign = center
}
